# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-24 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190320_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='None', upload_to='app1/static/images/'),
        ),
    ]
